# Начало playbook

# Этот блок описывает первый "play" в Ansible. 
# Он содержит описание того, что будет сделано на серверах группы "mikron_servers".
- name: Настройка серверов
  hosts: mikron_servers  # Указывает, что задачи выполняются на серверах из группы "mikron_servers" в вашем инвентаре
  become: yes  # Повышаем привилегии до root для выполнения административных задач

  tasks:
    # Задача 1: Обновление пакетов
    - name: Обновление пакетов
      apt:
        update_cache: yes      # Обновляем кэш пакетов
        upgrade: dist          # Обновляем все пакеты до последних версий
      # Модуль apt используется для работы с пакетами на Debian-based системах

    # Задача 2: Установка необходимых пакетов
    - name: Установка Git, curl, wget и других программ
      apt:
        name:
          - git
          - curl
          - wget
          # Добавьте другие пакеты по мере необходимости
        state: present          # Устанавливаем пакеты, если они не установлены
      # Этот модуль apt устанавливает несколько пакетов на сервер
