---
- name: Установка или удаление пакетов для серверов
  hosts: mikron_servers
  become: yes

  tasks:
    - name: Установка или удаление пакетов
      package:
        name: "{{ item }}"
        state: "{{ state }}" #present  # или absent, если хотите удалять
      loop: "{{ packages.split(',') | map('trim') | list }}"
      when: packages is defined
