---
- name: Установка или удаление пакетов для серверов
  hosts: mikron_servers
  become: yes
  
  tasks:
    - name: Установка или удаление пакетов
      package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ packages | flatten }}"
      when: packages is defined
