---
- name: Install and configure iperf3 with autostart
  hosts: all
  become: true

  tasks:
    - name: Set debconf selection for iperf3 autostart
      ansible.builtin.shell: echo "iperf3 iperf3/autostart boolean true" | debconf-set-selections

    - name: Install iperf3
      ansible.builtin.apt:
        name: iperf3
        state: present
        update_cache: yes

    - name: Enable and start iperf3 service
      ansible.builtin.service:
        name: iperf3
        enabled: yes
        state: started
