---
- name: Установка или удаление пакетов для серверов
  hosts: mikron_servers
  become: yes
  
  tasks:
    - name: Установка или удаление пакетов
      package:
        name: "{{ item }}"
        state: present  # Устанавливаем все пакеты, если нет состояния удаления
      loop: "{{ packages }}"
      when: packages is defined
