---
- name: Установка или удаление пакетов для серверов
  hosts: mikron_servers
  become: yes

  tasks:
    - name: Установка или удаление пакетов
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages | list }}"  # Преобразуем в список, если передано одно значение
      when: packages is defined
