---
- name: Add SSH key to authorized_keys
  hosts: all
  become: true
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Add public key to authorized_keys
      lineinfile:
        path: /root/.ssh/authorized_keys
        line: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        create: yes
        owner: root
        group: root
        mode: '0600'
