---
# Начало playbook

# Этот блок описывает первый "play" в Ansible. 
# Он содержит описание того, что будет сделано на серверах группы "web".
- name: Настройка веб-сервера
  hosts: mikron_servers  # Указывает, что задачи выполняются на серверах из группы "mikrons" в вашем инвентаре
  become: yes  # Повышаем привилегии до root для выполнения административных задач

  tasks:
    # Задача 1: Установка nginx
    - name: Установка nginx
      apt:
        name: nginx       # Указываем, какой пакет нужно установить (nginx)
        state: present    # Устанавливаем пакет, если он не установлен
      # Этот модуль apt будет использоваться для работы с пакетами на Debian-based системах

    # Задача 2: Проверка и запуск nginx
    - name: Проверка статуса nginx
      service:
        name: nginx         # Указываем имя сервиса (nginx)
        state: started      # Указываем, что сервис должен быть запущен
        enabled: yes        # Указываем, что сервис должен автоматически запускаться при старте системы
      # Модуль "service" используется для управления статусом сервисов, такими как nginx

    # Задача 3: Копирование конфигурации nginx
    #- name: Копирование конфигурации nginx
    #  copy:
    #   src: /path/to/local/nginx.conf  # Путь к локальному файлу на вашей машине
    #    dest: /etc/nginx/nginx.conf    # Путь к удаленному файлу, куда нужно скопировать конфигурацию
    #    mode: '0644'                    # Устанавливаем права доступа для файла (чтение/запись для владельца, только чтение для группы и других)
      # Модуль "copy" используется для копирования файлов с вашей локальной машины на удаленную машину

    # Задача 4: Перезапуск nginx для применения конфигурации
    - name: Перезапуск nginx
      service:
        name: nginx        # Указываем имя сервиса для перезапуска
        state: restarted   # Перезапускаем сервис
      # С помощью этой задачи мы перезапускаем nginx, чтобы он применил изменения конфигурации

# Конец playbook
