---
- name: Выполнение команд на серверах
  hosts: mikron_servers
  become: yes

  tasks:
    - name: Выполнение команд
      shell: "{{ item }}"
      loop: "{{ commands.split(',') | map('trim') | list }}"
      when: commands is defined
      register: command_outputs

    - name: Вывод результатов выполнения команд в столбик
      debug:
        msg: |
          Команда: {{ item.item }}
          Результат:
          {{ item.stdout_lines | join('\n') }}
          Ошибки:
          {{ item.stderr_lines | join('\n') }}
      loop: "{{ command_outputs.results }}"
      loop_control:
        label: "{{ item.item }}"
      vars:
        ansible_log_messages: true
