---
- name: Настройка SSH-доступа для кластера
  hosts: all  # Укажите группу серверов кластера из вашего inventory
  become: yes  # Поднимаем права до root
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_ansible

  tasks:
    # 1. Создание SSH-ключа на каждом сервере
    - name: Генерация SSH-ключа на серверах
      command: ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N ""
      args:
        creates: /root/.ssh/id_rsa  # Генерация будет пропущена, если ключ уже существует

    # 2. Скопировать публичный ключ главного сервера на сервера кластера
    - name: Копирование публичного ключа главного сервера
      copy:
        src: /root/.ssh/id_rsa_ansible.pub  # Абсолютный путь до публичного ключа
        dest: /root/.ssh/authorized_keys
        owner: root
        mode: '0600'

    # 3. Проверка входа по ключу
    - name: Проверка подключения по ключу
      shell: ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no root@{{ inventory_hostname }} exit
      register: ssh_check
      ignore_errors: true  # Игнорируем ошибки, чтобы обработать их вручную позже

    - name: Убедиться, что вход по ключу работает
      fail:
        msg: "Не удалось подключиться по ключу к серверу {{ inventory_hostname }}!"
      when: ssh_check.rc != 0  # Ошибка, если код возврата команды не равен 0

    # 4. Отключить вход по паролю
    - name: Отключить вход по паролю
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify:
        - Перезапуск SSH

    # 5. Повторная проверка подключения по ключу
    - name: Повторная проверка подключения по ключу
      shell: ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no root@{{ inventory_hostname }} exit
      register: final_ssh_check
      ignore_errors: true

    - name: Убедиться, что вход по ключу после отключения пароля работает
      fail:
        msg: "После отключения входа по паролю невозможно подключиться к серверу {{ inventory_hostname }}!"
      when: final_ssh_check.rc != 0

# Секция handlers должна находиться на том же уровне, что и tasks
  handlers:
    - name: Перезапуск SSH
      service:
        name: ssh
        state: restarted
