---
- name: Настройка SSH-доступа для кластера
  hosts: all  # Укажите группу серверов кластера из вашего inventory
  become: yes  # Поднимаем права до root
  vars:
    ansible_ssh_private_key_file: "/root/.ssh/id_rsa_ansible"  # Путь к приватному ключу на главном сервере

  tasks:
    # 1. Проверка существования публичного ключа главного сервера
    - name: Проверка существования публичного ключа главного сервера
      stat:
        path: /root/.ssh/id_rsa_ansible.pub
      register: key_check

    # 2. Остановить выполнение, если публичный ключ не найден
    - name: Остановить выполнение, если публичный ключ не найден
      fail:
        msg: "Публичный ключ /root/.ssh/id_rsa_ansible.pub не найден на главном сервере!"
      when: key_check.stat.exists == false

    # 3. Генерация SSH-ключа на серверах
    - name: Генерация SSH-ключа на серверах
      command: ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N ""
      args:
        creates: /root/.ssh/id_rsa  # Генерация будет пропущена, если ключ уже существует

    # 4. Копирование публичного ключа главного сервера на сервера кластера
    - name: Копирование публичного ключа главного сервера
      copy:
        src: /root/.ssh/id_rsa_ansible.pub  # Путь к публичному ключу главного сервера
        dest: /root/.ssh/authorized_keys  # Копирование в authorized_keys
        owner: root
        mode: '0600'

    # 5. Проверка подключения по ключу
    - name: Проверка подключения по ключу
      shell: ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no root@{{ inventory_hostname }} exit
      register: ssh_check
      ignore_errors: true  # Игнорируем ошибки, чтобы обработать их вручную позже

    - name: Убедиться, что вход по ключу работает
      fail:
        msg: "Не удалось подключиться по ключу к серверу {{ inventory_hostname }}!"
      when: ssh_check.rc != 0  # Ошибка, если код возврата команды не равен 0

    # 6. Отключить вход по паролю
    - name: Отключить вход по паролю
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify:
        - Перезапуск SSH

    # 7. Повторная проверка подключения по ключу
    - name: Повторная проверка подключения по ключу
      shell: ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no root@{{ inventory_hostname }} exit
      register: final_ssh_check
      ignore_errors: true

    - name: Убедиться, что вход по ключу после отключения пароля работает
      fail:
        msg: "После отключения входа по паролю невозможно подключиться к серверу {{ inventory_hostname }}!"
      when: final_ssh_check.rc != 0

  handlers:
    - name: Перезапуск SSH
      service:
        name: ssh
        state: restarted
