---
- name: Настройка SSH-доступа для кластера
  hosts: all
  become: yes  # Поднимаем права до root
  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    ansible_ssh_public_key_file: /root/.ssh/id_rsa.pub

  tasks:
    # 1. Проверка существования публичного ключа на контроллере
    - name: Проверка наличия публичного ключа на контроллере
      stat:
        path: /root/.ssh/id_rsa.pub
      register: key_check

    - name: Остановить выполнение, если публичный ключ не найден
      fail:
        msg: "Публичный ключ /root/.ssh/id_rsa.pub не найден на главном сервере!"
      when: not key_check.stat.exists

    # 2. Копирование публичного ключа с контроллера на сервера кластера
    - name: Копирование публичного ключа на сервера кластера
      copy:
        src: /root/.ssh/id_rsa.pub  # Путь к публичному ключу на контроллере
        dest: /root/.ssh/authorized_keys  # Местоположение на удалённых серверах
        owner: root
        mode: '0600'
        append: yes  # Добавляем ключ в конец файла, не перезаписывая его
      when: key_check.stat.exists
      notify: Restart SSH

    # 3. Проверка подключения по SSH с использованием ключа
    - name: Проверка подключения по ключу
      shell: ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no root@{{ inventory_hostname }} exit
      register: ssh_check
      ignore_errors: true  # Игнорируем ошибки, чтобы обработать их вручную позже

    - name: Убедиться, что вход по ключу работает
      fail:
        msg: "Не удалось подключиться по ключу к серверу {{ inventory_hostname }}!"
      when: ssh_check.rc != 0  # Ошибка, если код возврата команды не равен 0

    # 4. Отключить вход по паролю
    - name: Отключить вход по паролю
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify:
        - Перезапуск SSH

    # 5. Повторная проверка подключения по ключу
    - name: Повторная проверка подключения по ключу после отключения пароля
      shell: ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no root@{{ inventory_hostname }} exit
      register: final_ssh_check
      ignore_errors: true

    - name: Убедиться, что вход по ключу после отключения пароля работает
      fail:
        msg: "После отключения входа по паролю невозможно подключиться к серверу {{ inventory_hostname }}!"
      when: final_ssh_check.rc != 0

  handlers:
    - name: Перезапуск SSH
      service:
        name: ssh
        state: restarted
