- name: Настройка SSH-доступа для кластера
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  #become_password: "{{ sudo_password }}"
  tasks:
    - name: Проверка наличия публичного ключа на контроллере
      stat:
        path: /root/.ssh/id_rsa.pub
      register: ssh_key_stat
      ignore_errors: true

    - name: Остановить выполнение, если публичный ключ не найден
      fail:
        msg: "Публичный ключ не найден на контроллере."
      when: not ssh_key_stat.stat.exists

    - name: Копирование публичного ключа на сервера
      become: true
      become_user: root
      slurp:
        src: /root/.ssh/id_rsa.pub
      register: slurped_key
      delegate_to: localhost
      when: ssh_key_stat.stat.exists

    - name: Создание директории для ключей на целевых серверах
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'

    - name: Добавление публичного ключа на сервера
      authorized_key:
        user: root
        state: present
        key: "{{ slurped_key.content | b64decode }}"
        path: /root/.ssh/authorized_keys
      when: ssh_key_stat.stat.exists

    - name: Отключение парольного доступа
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Перезапуск SSH

  handlers:
    - name: Перезапуск SSH
      service:
        name: sshd
        state: restarted
