---
# Начало playbook

- name: Обновление системы на серверах
  hosts: all  # Применяем playbook ко всем хостам, указанным в инвентаре
  become: yes  # Повышаем привилегии до root для выполнения административных команд

  tasks:
    # Задача 1: Обновление списка пакетов
    - name: Обновить кэш пакетов APT
      apt:
        update_cache: yes  # Включаем обновление кэша пакетов
        cache_valid_time: 3600  # Кэш будет считаться актуальным в течение 1 часа

    # Задача 2: Обновление всех установленных пакетов
    - name: Установить обновления для всех пакетов
      apt:
        upgrade: dist  # Выполняем полное обновление системы (equivalent to `apt upgrade -y`)

    # Задача 3: Очистка ненужных пакетов (опционально)
    - name: Очистка ненужных пакетов и зависимостей
      apt:
        autoremove: yes  # Удаляем неиспользуемые пакеты
        autoclean: yes   # Чистим кэш APT

# Конец playbook
